module.exports = {
  // Authentication Errors
  AUTH_INVALID_CREDENTIALS: "AUTH_INVALID_CREDENTIALS",
  AUTH_MISSING_TOKEN: "AUTH_MISSING_TOKEN",
  AUTH_INVALID_TOKEN: "AUTH_INVALID_TOKEN",
  AUTH_UNAUTHORIZED: "AUTH_UNAUTHORIZED",

  // User Errors
  USER_EXISTS: "USER_EXISTS",
  USER_NOT_FOUND: "USER_NOT_FOUND",
  USER_INACTIVE: "USER_INACTIVE",
  USER_ROLE_INVALID: "USER_ROLE_INVALID",

  // Server Errors
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",

  // Validation Erros
  VALIDATION_ERROR: "VALIDATION_ERROR",
};
