module.exports = {
  // Authentication Errors
  AUTH_INVALID_CREDENTIALS: "AUTH_INVALID_CREDENTIALS",
  AUTH_UNAUTHORIZED: "AUTH_UNAUTHORIZED",
  AUTH_FORBIDDEN: "AUTH_FORBIDDEN",

  // User Errors
  USER_EXISTS: "USER_EXISTS",
  USER_NOT_FOUND: "USER_NOT_FOUND",
  USER_INACTIVE: "USER_INACTIVE",
  USER_ROLE_INVALID: "USER_ROLE_INVALID",

  // Restaurant Errors
  RESTAURANT_EXISTS: "RESTAURANT_EXISTS",
  RESTAURANT_NOT_FOUND: "RESTAURANT_NOT_FOUND",
  RESTAURANT_INACTIVE: "RESTAURANT_INACTIVE",

  //Menu item Errors
  MENU_ITEM_EXISTS: "MENU_ITEM_EXISTS",
  MENU_ITEM_NOT_FOUND: "MENU_ITEM_NOT_FOUND",

  // Category Errors
  CATEGORY_NOT_FOUND: "CATEGORY_NOT_FOUND",
  CATEGORY_EXISTS: "CATEGORY_EXISTS",

  // Table Errors
  TABLE_EXISTS: "TABLE_EXISTS",
  TABLE_NOT_FOUND: "TABLE_NOT_FOUND",

  // Table Location Errors
  LOCATION_NOT_FOUND: "LOCATION_NOT_FOUND",
  LOCATION_EXISTS: "LOCATION_EXISTS",

  // Table Shape Errors
  SHAPE_NOT_FOUND: "SHAPE_NOT_FOUND",
  SHAPE_EXISTS: "SHAPE_EXISTS",

  // Server Errors
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",

  // Validation Erros
  VALIDATION_ERROR: "VALIDATION_ERROR",

  //Invalid JSON
  INVALID_JSON_PAYLOAD: "INVALID_JSON_PAYLOAD",
};
