module.exports = {
  // Authentication Errors
  AUTH_INVALID_CREDENTIALS: "AUTH_INVALID_CREDENTIALS",
  AUTH_UNAUTHORIZED: "AUTH_UNAUTHORIZED",

  // User Errors
  USER_EXISTS: "USER_EXISTS",
  USER_NOT_FOUND: "USER_NOT_FOUND",
  USER_INACTIVE: "USER_INACTIVE",
  USER_ROLE_INVALID: "USER_ROLE_INVALID",

  // Restaurant Errors
  RESTAURANT_EXISTS: "USER_EXISTS",
  RESTAURANT_NOT_FOUND: "RESTAURANT_NOT_FOUND",
  RESTAURANT_INACTIVE: "RESTAURANT_INACTIVE",

  // Server Errors
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",

  // Validation Erros
  VALIDATION_ERROR: "VALIDATION_ERROR",

  //Invalid JSON
  INVALID_JSON_PAYLOAD: "INVALID_JSON_PAYLOAD",
};
